### ISSUE TITLE
Prototype naar html

### ISSUE THREAD

**Issue by ColindeGroot** [ColindeGroot/the-client-website#1]
sitemap:
![20240925_114342.jpg](https://github.com/user-attachments/assets/460c307f-9ee7-41bc-a906-712eb20b5ced)

design:
![20240925_114326.jpg](https://github.com/user-attachments/assets/db0a57fc-a107-4c88-a835-65602ac12069)

workflow:
![20240925_114314.jpg](https://github.com/user-attachments/assets/e3603ff0-0315-4ae2-aec2-cd6161a7cc9a)

bestaand figma ontwerp:

ontwerp homepage: https://www.figma.com/design/PbMAVjDmeSEX5hj85mbNhB/Webinar-RT?node-id=1-9145&m=dev&t=HT5gxMIBadaduRee-1

https://www.figma.com/design/PbMAVjDmeSEX5hj85mbNhB/Webinar-RT?node-id=0-1&node-type=canvas&t=yt3sXJqS48Eh6tmR-0

**Comment by Naddybs** [comment]
Je schetsen zien er voor het algemeen goed uit. Misschien de afbeeldingen er beter in plaatsen zodat ik mijn laptop niet hoef te draaien 🙃. Je figma schetsen zien er echt heel goed uit! Ben benieuwd wat het eindresultaat gaat zijn.
