### ISSUE TITLE
layout in css

### ISSUE THREAD

**Issue by ColindeGroot** [ColindeGroot/the-client-website#6]
feedback over layout kan hier

**Comment by julesbruins** [comment]
- Bij de hover in de navigatie bar is het mooier als alle blokjes even groot zijn bijvoorbeeld.
- Gebruik ipv allemaal losse paddings alleen op de main alleen een padding/margin. 
- .webinar-articles zijn niet gelijk aan het figma ontwerp.
- Bovenin de body staat heel random 'author' wat is dit???
